robot:
  name: $name
  creature: $creature
  firstPage: on
  autoStart: on
  camera: off
  virtualBot: 0

info:
  version: dev_gen2
  logfile: /tmp/puppet-master.log
  serviceNetwork: rpi-access-point.service
  updateURL: https://raw.githubusercontent.com/poppy-project/raspoppy/master/auto-update.sh
  board: $board

hotspot:
  start: on
  confFile: /boot/hotspot.txt
  ssid: Poppy-Hotspot
  psk: poppyproject

wifi:
  start: off
  confFile: /etc/wpa_supplicant/wpa_supplicant.conf
  ssid: Poppy-Router
  psk: poppyproject

services:
  PuppetMaster: puppet-master.service
  JupyterNotebook: jupyter-notebook.service
  PoppyDocs: poppy-docs.service
  PoppyViewer: poppy-viewer.service

poppyLog:
  puppetMaster: /tmp/puppet-master.log
  jupyter: /tmp/jupyter.log
  update: /tmp/poppy-update.log
  docs: /tmp/poppy-docs.log
  viewer: /tmp/poppy-viewer.log
  virtualBot: /tmp/virtual-bot.log
  configMotor: /tmp/motor-config.log

poppyPort:
  puppetMaster: 2280
  jupyter: 8888
  docs: 4000
  viewer: 8000
  http: 8080
  snap: 6969
  ws: 9009
