robot:
  name: $name
  creature: $creature
  camera: off

info:
  version: 1.0
  logfile: /tmp/puppet-master.log
  board: $board

update:
  url: https://raw.githubusercontent.com/poppy-project/raspoppy/master/auto-update.sh
  logfile: $home/.install.log
  lockfile: /tmp/poppy-update-pid.lock

poppy_configure:
  logfile: /tmp/poppy-config.log
  poppup_startup: on

wifi:
  hostspot_conf_file: /boot/hotspot.txt
  hostspot_service: rpi-access-point
  default_ssid: Poppy Hotspot
  default_password: poppyproject
